first_name = input("First Name: ")
last_name = input("Last Name: ") 
email_address = input("Email Address: ")
phone_number = input("Phone Number: ")
job_title = input("Job Title: ")
id_number = input("ID Number: ")
hair_color = input("Hair Color: ")
eye_color = input("Eye Color: ")
month = input("Month Of Start: ")
training = input("Have You Completed Advanced Training: ")

print("The ID Card Is:")
print(f"----------------------------------------")
print(f"{last_name.upper()}, {first_name.capitalize()}")
print(f"{job_title.capitalize()}")
print(f"ID: {id_number}")
print()
print(f"{email_address.lower()}")
print(f"{phone_number}")
print()
print(f"{'Hair: ' + hair_color.capitalize():<20} Eye: {eye_color.capitalize()}")
print(f"{'Month: ' + month.capitalize():<20} Training: {training.capitalize()}")
print(f"-----------------------------------------")