age = int(input("How old are you? "))
print()
print(f"You will be {age + 1} years old on your next birthday. ")
print()
carton = int(input("How many egg cartons do you have? "))
print()
print(f"You have {carton * 12} eggs.")
print()
cookies = int(input("How many cookies do you have? "))
print()
people = int(input("How many people are there? "))
print()
print(f"There are {cookies // people} whole cookies per person. ")
